### ISSUE TITLE
Dependency on happy

### ISSUE THREAD

**Issue by niklasbroberg** [haskell-suite/haskell-src-exts#14]
HSE has an implicit dependency on happy for the parser. If happy isn't already installed then cabal install HSE doesn't work, it would be great if this could be fixed. This problem has shown up for real users trying to install both derive and hlint - failing when installing HSE because of the lack of happy.

Related to this deficiency in cabal-install: http://hackage.haskell.org/trac/hackage/ticket/227

**Comment by mulchy** [comment]
+1 this should be added to the dependencies

**Comment by pjonsson** [comment]
All those who suggest that happy should be added to the dependencies: does that resolve your problem if happy is not in your path?

**Comment by 3noch** [comment]
All that matters is that we *know* why the build failed.

**Comment by 3noch** [comment]
To clarify, the build could fail much sooner in dependency resolution instead of build phase with an easy check: "I need happy; is it on the path? No. Fail immediately."

**Comment by pjonsson** [comment]
And I'm asking whether the build fails with a proper error message if you have happy installed but not in your path.

**Comment by feuerbach** [comment]
happy is an executable, not library. GHC doesn't track it in its package database, and you cannot depend on it in the cabal file (the dependency will never be satisfied, regardless of whether happy is installed and/or in PATH).

This issue isn't about adding a line to the cabal file. Rather it's about:

* waiting for https://github.com/haskell/cabal/issues/220 to be addressed in some way
* building upon their solution

**Comment by Dschee** [comment]
Hello, I just encountered a problem installing `ghc-mod` (this library couldn't be installed) and luckily could find the issue pretty quickly: I needed to install happy first. After running `cabal install happy` it all worked – so I agree with all my predecessors: `happy` should be added to the dependencies. The issue you are linking to still isn't solved either ... just saying.

**Comment by mpickering** [comment]
Fairly sure this is fixed now by `Build-Tools` dependencies.

**Comment by Arcanemagus** [comment]
Just a note, this isn't fixed yet as of the released version `1.20.2`:
```
Failed to install haskell-src-exts-1.20.2
Build log ( /home/atom/.cabal/logs/haskell-src-exts-1.20.2.log ):
cabal: Entering directory '/tmp/cabal-tmp-855/haskell-src-exts-1.20.2'
Configuring haskell-src-exts-1.20.2...
cabal: The program 'happy' version >=1.19 is required but it could not be
found.
cabal: Leaving directory '/tmp/cabal-tmp-855/haskell-src-exts-1.20.2'
```

After manually running `cabal install happy` the building of `haskell-src-exts` worked correctly.
