### ISSUE TITLE
PatternSynonyms not supported

### ISSUE THREAD

**Issue by mpickering** [haskell-suite/haskell-src-exts#194]
I'm using stylish-haskell (0.5.11.0) which depends on haskell-src-exts 1.16. The parse fails when encountering this pattern synonym. 

```
pattern CommandTrigger msg <- (T.uncons -> Just ('@', msg))
```

**Comment by ndmitchell** [comment]
I'm also seeing errors reported at https://github.com/ndmitchell/hlint/issues/109 by @jaseemabid: 

    pattern If predicate conseq alt = List [Atom "if", predicate, conseq, alt]
    pattern Defun name args body = List [Atom "defun", Atom name, List args, body]
    pattern Let args body = List [Atom "let", args, body]
    pattern Quote = Atom "quote"
    pattern Set var val = List [Atom "set!", (Atom var), val]

**Comment by ndmitchell** [comment]
@mpickering points out that patterns such as `pattern (A a) = Just a` don't cause parse errors because it is parsed as a function declarations.

**Comment by mpickering** [comment]
I am working on implementing `PatternSynonyms`.

**Comment by ndmitchell** [comment]
This blocks some users, for example @ekmett from using HLint:
http://www.reddit.com/r/haskell/comments/33n76x/why_is_vs_datamonoidmappend_v_better_than_vs_v/cqocq33

**Comment by eigengrau** [comment]
This also affects import statements that import pattern synonyms.

```
import Foo.Bar (pattern SomePattern)
```

**Comment by pjonsson** [comment]
I just merged @mpickering's implementation of PatternSynonyms so I'll close this ticket.

**Comment by eigengrau** [comment]
I just rebuilt both hlint and stylish-haskell based on the current haskell-src-ext HEAD. Barring some sandbox-issue on my side, haskell-src-exts still fails to parse pattern synonym imports.

I. e., I ran hlint and stylish-haskell over a file that defines patterns and exports them; this seems to work now (which led me to believe the rebuild worked and these programs are now using haskell-src-ext HEAD). However, when supplying a file that contains `import Foo.Bar (pattern SomePattern)`, I still get a parse error. E. g., stylish-haskell reports:

```
Language.Haskell.Stylish.Parse.parseModule: could not parse src/YampaGame/Main.hs: ParseFailed (SrcLoc "<unknown>.hs" 29 45) "Parse error: pattern"
```

Can you reproduce?

**Comment by pjonsson** [comment]
@eigengrau: it looks like patterns are missing from `impspec` in the patch I merged. Please file a new bug for that issue.

**Comment by eigengrau** [comment]
#262
